lenra-io/client_common

.github/workflows/generate_and_deploy_doc.yml

ci: Generate and deploy doc

---

lib/api/lenra_http_client.dart

fix: HTTP Response now parsed properly

---

lib/views/verify_code/verifiying_code_page.dart

feat: Rephrase registration message

---

lib/api/request_models/login_request.dart
lib/api/user_api.dart
lib/models/auth_model.dart
lib/views/login/login_form.dart
pubspec.lock
test/api/request_models/login_request_test.dart

feat: keep connection

---

lib/models/build_model.dart
lib/models/user_application_model.dart
pubspec.lock

Linked to https://github.com/lenra-io/client-backoffice/issues/44

feat!: Rework `selectedApp` variable for backoffice + Add `latestBuildForApp` method

---

lib/api/application_api.dart
lib/models/user_application_model.dart

Linked to https://github.com/lenra-io/Lenra/issues/183
Added a API method to get all apps a user has opened at least once.

feat: Application API request (apps user opened)

---

lib/api/request_models/validate_dev_request.dart
lib/models/auth_model.dart

Linked to https://github.com/lenra-io/Lenra/issues/188

feat: Remove dev token

---

lib/views/login/login_form.dart

Closes https://github.com/lenra-io/client-common/issues/62

fix: Keep me logged in - Alignment

---

pubspec.lock
pubspec.yaml

fix: Update dependencies

---

lib/api/user_api.dart
lib/models/auth_model.dart
lib/views/verify_code/verify_code_form.dart

feat: resend button

---

lib/navigator/common_navigator.dart
lib/navigator/guard.dart

Linked to https://github.com/lenra-io/client/issues/48

fix: Navigation back button

---

lib/views/simple_page.dart
pubspec.lock

#__ 
Fixed an error where having a Scrollbar + SingleChildScrollView would cause an error when scrolling because the Scrollbar is not attached to any ScrollView. 
We do not need to show the Scrollbar for the SimplePage widget because it is only used for relatively small views and the scroll bar would be useless for such content.
The scroll bar is still shown on non-mobile platforms such as Linux, windows and dev thanks to the SingleChildScrollView.
Here is the error : 
```console
Exception has occurred.
FlutterError (The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being …
```

fix: Scrollbar error

---

lib/navigator/common_navigator.dart

feat: Add SafeArea

---

pubspec.lock
pubspec.yaml

feat: Upgrade lenra_components to v1.0.0-beta.52 feat: Radio unselected color (#122)

feat: Update dependencies

---

lib/api/application_api.dart
lib/api/response_models/deployment_response.dart
lib/api/response_models/deployments_response.dart
lib/config/config.dart
lib/models/deployment_model.dart
pubspec.lock

https://github.com/lenra-io/lenra_cli/issues/148

feat: add deployment model

---

lib/navigator/guard.dart

fix: Do not override redirect each time _toAuth is triggered

---

lib/models/auth_model.dart
lib/views/auth/auth_page_form.dart
lib/views/auth/login_form.dart
lib/views/auth/register_form.dart
pubspec.lock

fix: Show errors on login and register

---

pubspec.yaml

This PR just change the dependency link to https instead of sh, that allow to not need the deploy key to get the dependencies

build: Migrate SSH dependencies to HTTPS

---

.github/workflows/flutter.yml
.github/workflows/generate_and_deploy_doc.yml
.github/workflows/semantic_release.yml
pubspec.lock
pubspec.yaml

We needed a way to make the Catcher dependency work on Desktop. The main project is not maintained anymore by its creator. The community created a fork with some fixes of the main project, it is not meant to expect features, only fixes. 
Maybe the creator of the main project will come back and accept the merge requests. For now, we have to use this fork.

fix: Use Catcher dependency from fork

---

.github/workflows/flutter.yml

Closes #99 
We need to remove each PR-IS-WIP action call because it's broken

ci: We need to remove each PR-IS-WIP action call because it's broken

---

lib/oauth/oauth_model.dart

Closes # 
There was a problem when trying to run the OAuth on a iOS environment. The app would not catch the event from the integrated browser. To fix it, we just need to handle iOS the same as Android as you can see in the changes.

fix: Add iOS case in platform uri scheme

---

lib/oauth/oauth_model.dart

Closes https://github.com/lenra-io/client_common/issues/106

fix: Use Config's oauthBaseUrl for disconnect
